# Generated by Django 2.0.1 on 2018-01-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_auto_20180120_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='vacuna',
            field=models.ManyToManyField(blank=True, to='mascotas.Vacunas'),
        ),
    ]
